name: Javascript Task - CI/CD
on: push
jobs:
Test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: echo "this job automatically triggered by ${{ github.event_name}} event"
    - run: Module.3

    messageSlack:
      runs-on: ubuntu-latest
      steps:
       - name: Notification Slack
         uses: rtCamp/action-slack-notify@v2
         env:
         SLACK_CHANNEL: task-review
         SLACK_TITLE: Happiness-CI/CD  
         SLACK_WEBHOOK: ${{secret.SLACK_WEBHOOK_UR }}
         status: ${{ job.status }}